spring:
  application:
    name: authserver
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  datasource:
    url: "jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC"
    username: test
    password:
  dbcp2:
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        open-in-view: false
    generate-ddl: true

jwt:
  token:
    header: api_key
    issuer: auth_demo_security
    clientSecret: Wlc1V01XSkdPV3RhVnpGMldESkdNV1JIYUdaaE1sWTE
    expirySeconds: 0

server:
  port: 9090
