zuul:
  routes:
    auth:
      path: /api/**
      url: http://localhost:9090/api
    foos:
      path: /foos/**
      url: http://localhost:8081/foos
    bars:
      path: /bars/**
      url: http://localhost:8082/bars